### ISSUE TITLE
listing buckets

### ISSUE THREAD

**Issue by cogitor** [TuneOSS/fasts3#16]
Not sure if you've planned to implement it, but fasts3 doesn't list buckets like s3cmd would e.g.
`fasts3 ls` or `fasts3 ls s3://` doesn't return anything while `s3cmd ls` or `s3cmd ls s3://` would return the list of available buckets.

IMO this would be a nice addition, especially if combined with command completion. But feel free to close this if it doesn't match your plans for the tool :)

**Comment by rushton** [comment]
👍 sounds like a good addition. Also feel free to contribute if you have the time to, otherwise I will get around to it when I have some free time.

**Comment by rushton** [comment]
now live in version 1.2.4

**Comment by cogitor** [comment]
Awesome, cheers! I've seen there are also efforts fixing the issues with different regions as well 👍  
Keep up the good work :)
